const ExpensesActionTypes = {
	ADD_EXPENSE: 'ADD_EXPENSE',
	DELETE_EXPENSE: 'DELETE_EXPENSE',
	EDIT_ENTRY_VALUE: 'EDIT_ENTRY_VALUE',
	RECALCULATE_TIME_SPENT: 'RECALCULATE_TIME_SPENT'
}

export default ExpensesActionTypes
