const ExpensesActionTypes = {
	ADD_EXPENSE: 'ADD_EXPENSE',
	DELETE_EXPENSE: 'DELETE_EXPENSE',
	EDIT_ENTRY_VALUE: 'EDIT_ENTRY_VALUE',
	RECALCULATE_TIME_SPENT: 'RECALCULATE_TIME_SPENT',
	SET_CATEGORY_BUDGET: 'SET_CATEGORY_BUDGET',
	UPDATE_MOTHNY_CATEGORY_BUDGET: 'UPDATE_MOTHNY_CATEGORY_BUDGET'
}

export default ExpensesActionTypes
