const BudgetActionTypes = {
	BUDGET_ADD_INCOME: 'BUDGET_ADD_INCOME',
	BUDGET_ADD_EXPENSE: 'BUDGET_ADD_EXPENSE',
	BUDGET_DELETE_EXPENSE: 'BUDGET_DELETE_EXPENSE',
	BUDGET_DELETE_INCOME: 'BUDGET_DELETE_INCOME',

	EDIT_ENTRY_VALUE: 'EDIT_ENTRY_VALUE',
	GET_TOTAL_BUDGET: 'GET_TOTAL_BUDGET',
	GET_ALL_EXPENSES: 'GET_ALL_EXPENSES',
	GET_ALL_INCOME: 'GET_ALL_INCOME',
	SORT_BY_AMOUNT_ASC: 'SORT_BY_AMOUNT_ASC',
	SORT_BY_AMOUNT_DESC: 'SORT_BY_AMOUNT_DESC'
}

export default BudgetActionTypes
