const BudgetActionTypes = {
	BUDGET_ADD_INCOME: 'BUDGET_ADD_INCOME',
	BUDGET_ADD_EXPENSE: 'BUDGET_ADD_EXPENSE',
	BUDGET_DELETE_EXPENSE: 'BUDGET_DELETE_EXPENSE',
	BUDGET_DELETE_INCOME: 'BUDGET_DELETE_INCOME',
	BUDGET_EDIT_ON_INC: 'BUDGET_EDIT_ON_INC',
	BUDGET_EDIT_ON_EXP: 'BUDGET_EDIT_ON_EXP'
}

export default BudgetActionTypes
