const BudgetActionTypes = {
	ADD_INCOME: 'ADD_INCOME',
	ADD_EXPENSE: 'ADD_EXPENSE',
	DELETE_EXPENSE: 'DELETE_EXPENSE',
	DELETE_INCOME: 'DELETE_INCOME',
	EDIT_ENTRY_VALUE: 'EDIT_ENTRY_VALUE',
	GET_TOTAL_BUDGET: 'GET_TOTAL_BUDGET',
	GET_ALL_EXPENSES: 'GET_ALL_EXPENSES',
	GET_ALL_INCOME: 'GET_ALL_INCOME',
	SORT_BY_AMOUNT_ASC: 'SORT_BY_AMOUNT_ASC',
	SORT_BY_AMOUNT_DESC: 'SORT_BY_AMOUNT_DESC'
}

export default BudgetActionTypes
